### ISSUE TITLE
Migrate to Jetpack Compose

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/cert4android#10]
There's currently just [`TrustCertificateActivity`](https://github.com/bitfireAT/cert4android/blob/main/src/main/java/at/bitfire/cert4android/TrustCertificateActivity.kt) in cert4android, so we can migrate it to Jetpack Compose, and see how it goes, before migrating icsx5 and the bigger projects.

Steps:
- [x] Disable `dataBinding` and enable `compose`
- [x] Configure Jetpack Compose
  - [x] Configure app's build.gradle
  - [x] Add dependencies
- [ ] ~Add [Accompanist Theme Adapter](https://google.github.io/accompanist/themeadapter-material/) for testing automatic theme migration.~
- [x] Migrate all the UI inside `TrustCertificateActivity`
- [x] Remove `activity_trust_certificate` from layouts.
- [x] Remove all the XML libraries from build.gradle

**Comment by rfc2822** [comment]
> Add [Accompanist Theme Adapter](https://google.github.io/accompanist/themeadapter-material/) for testing automatic theme migration.

Do we have to add that here or in the apps that embeds cert4android?

**Comment by ArnyminerZ** [comment]
> Do we have to add that here or in the apps that embeds cert4android?

That just converts the XML theme to Jetpack Compose, so it's only required here. In fact, we should probably simply create a custom Compose theme for cert4android using the [Theme Builder](https://m3.material.io/theme-builder#/dynamic). 

However, if some application is currently overriding the XML theme for some reason, which I don't know, we should stick with the XML theme, and use Accompanist Theme Adapter.

The thing is that Jetpack Compose uses a completely different theming approach than the XML design. The designing way is to build a kind of tree of modules inside modules. So for example, you create the main app theme, and call it `AppTheme`, the syntax would be:
```kotlin
AppTheme {
  // Everything that is inside of here will be themed with AppTheme
}
// Everything here won't be themed
```
So what Accompanist's Theme Adapter does is to create a theme called `MdcTheme`, which is made from the styles stored in the XML styles, and linked though the manifest. By default

**Comment by rfc2822** [comment]
I'm afraid that I still don't understand it 😢

> In fact, we should probably simply create a custom Compose theme for cert4android using the [Theme Builder](https://m3.material.io/theme-builder#/dynamic).

Will it then use the colors of the embedding application?

Currently cert4android uses the DAVx5 colors for DAVx5 and ICSx5 colors for ICSx5.

**Comment by ArnyminerZ** [comment]
If we create the custom theme no, that's why I suggested using Theme Adapter. Using this library "third-party" applications such as ICSx⁵ or DAVx⁵ can modify the colors.

**Comment by rfc2822** [comment]
Ok, then the theme-adapter would take the XML values from the application, right?

But what's the Compose-native way? If ICSx⁵ was completely Compose (without XML) and cert4android was completely Compose, how could cert4android be themed like ICSx5?

**Comment by ArnyminerZ** [comment]
> Ok, then the theme-adapter would take the XML values from the application, right?

Correct

> But what's the Compose-native way?

Nope

> If ICSx⁵ was completely Compose (without XML) and cert4android was completely Compose, how could cert4android be themed like ICSx5?

That's actually a good question, I'll take a look at it and see what's the "official" approach

**Comment by ArnyminerZ** [comment]
Okay, so after thinking and searching about this for a bit. I think the best option would be to pass the color as an extra to the Activity. So have a default/fallback color for the theme, and if when launching the activity and extra with the color is passed, override the default one.

**Comment by ArnyminerZ** [comment]
Here's an screenshot of the current design:
![Screenshot_20230417_194632](https://user-images.githubusercontent.com/12086466/232567900-c5b8cd05-35e4-4d03-a8b6-c83621be611e.png)

The theme in this case is provided by the system, for Android S+.
