### ISSUE TITLE
Continuous request of certificate verification

### ISSUE THREAD

**Issue by ArnyminerZ** [bitfireAT/cert4android#28]
Reference: https://github.com/bitfireAT/davx5-ose/discussions/411

**Comment by ArnyminerZ** [comment]
I think the issue might come from the saving of the certificate in `CustomCertStore`. We are never saving the updates from the Keystore object to the file. The only time we really save the changes is in `clearUserDecisions`:

https://github.com/bitfireAT/cert4android/blob/d6fd79807a2a7cb65c87bd90ac9ad7810fab199b/lib/src/main/java/at/bitfire/cert4android/CustomCertStore.kt#L81

We should also save in

https://github.com/bitfireAT/cert4android/blob/d6fd79807a2a7cb65c87bd90ac9ad7810fab199b/lib/src/main/java/at/bitfire/cert4android/CustomCertStore.kt#L142-L149

https://github.com/bitfireAT/cert4android/blob/d6fd79807a2a7cb65c87bd90ac9ad7810fab199b/lib/src/main/java/at/bitfire/cert4android/CustomCertStore.kt#L149-L156

**Comment by ArnyminerZ** [comment]
To reproduce:
1. Launch the sample app.
2. Trust a certificate
3. Try to trust again, it's already been trusted
4. Close the app (also from recents just in case)
5. Open the app again
6. The certificate can be trusted again, changes are not persisted.

**Comment by rfc2822** [comment]
Haha nice, thanks for the report. So: core functionality broken. Could be time for some tests ^^

**Comment by ArnyminerZ** [comment]
Yup, quite a serious bug 😅

**Comment by rfc2822** [comment]
At least easy to fix :)

**Comment by ArnyminerZ** [comment]
Maybe we want to add a test for this, I've tested this and it detects the issue on the main branch:
```kotlin
    @Test
    fun testPersistingChanges() {
        addTrustedCertificate()

        // Dispose the keystore - load keystore again
        certManager.certStore.loadUserKeyStore()

        // Check it has been trusted
        certManager.checkServerTrusted(siteCerts!!.toTypedArray(), "RSA")
    }
```
However, it needs to expose `certStore` and `loadUserKeyStore` through the `VisibleForTesting` annotation.
