### ISSUE TITLE
If CN is invalid with given domain or IP no connection is established (and also no prompt to continue explicitly)

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/cert4android#31]
People report that they are now unable to connect DAVx5 to their server in certain certificate use cases. It seems that our handling is correct, and in the past this was wrong. But maybe we can give them an option to accept the certificate anyway?

```
curl https://mail.elestra.si:2080/
curl: (60) SSL: no alternative certificate subject name matches target host name '[mail.elestra.si](http://mail.elestra.si/)'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above
```

Ticket references:

https://bitfire-at.zammad.com/#ticket/zoom/2632
https://bitfire-at.zammad.com/#ticket/zoom/2620

**Comment by rfc2822** [comment]
Yes, this happens when a certificate is valid, but for another hostname than specified ("bad hostname" scenario).

It's possible that in previous cert4android versions, we allowed to accept such certificates, too.
