### ISSUE TITLE
Fix code scanning alert - Use of a broken or risky cryptographic algorithm

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/cert4android#6]
Is MD5 secure enough to display a fingerprint to let users decide whether the certificate is trusted? Otherwise just keep SHA1

Tracking issue for:
- [ ] https://github.com/bitfireAT/cert4android/security/code-scanning/1

**Comment by rfc2822** [comment]
Browsers show SHA-1 and SHA-256 (and no MD5), so I think we can remove MD5 too:

![Bildschirmfoto vom 2022-11-29 14-56-27](https://user-images.githubusercontent.com/156167/204547984-30fede2c-7bd4-425c-8e46-4e96303666f9.png)

**Comment by ArnyminerZ** [comment]
Well, MD5 is not proper hashing, so I understand that it might be deprecated. I would personally use SHA-1.

For the end user it's almost the same, just numbers and letters.

**Comment by rfc2822** [comment]
Fixed with 683d2119e21fa014abfcb152bc4570b2db728a07
